### ISSUE TITLE
Problem z ustawieniem sensora

### ISSUE THREAD

**Issue by pniewiadowski** [PiotrMachowski/Home-Assistant-custom-components-Rozkladzik#5]
Cześć,

chciałem dodać przystanek jak poniżej:

```
  - platform: rozkladzik
    city: 'poznan'
    stops:
      - id: 5
        name: 'Szarych Szeregow'
        directions:
          - "Boranta"
```

ale w logach po restarcie HA dostaje taką wiadomość:

```
Szczegóły loga (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/rozkladzik/sensor.py:181
Integration: Sensor (documentation, issues)
First occurred: 14:33:08 (1 occurrences)
Last logged: 14:33:08
Error while setting up rozkladzik platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rozkladzik/sensor.py", line 49, in setup_platform
    dev.append(RozkladzikSensor(entity_id, name, city, stop_id, stop_name, group_mode, lines, directions))
  File "/config/custom_components/rozkladzik/sensor.py", line 60, in __init__
    self._city_data = self.get_city_data()
  File "/config/custom_components/rozkladzik/sensor.py", line 181, in get_city_data
    linesData = lines[11].split("#!#")
IndexError: list index out of range
```

**Comment by PiotrMachowski** [comment]
Cześć,

Z tego, co widzę, to podałeś złe id przystanku, prawdopodobnie powinieneś użyć `55917`

**Comment by pniewiadowski** [comment]
Dzięki za podpowiedź.
W takim razie zrobię PR do dokumentacji bo masz że do `id` trzeba podać wartość z pola `t` lub `b` a `55917` pochodzi tak na prawdę z pola `sid` chyba, że źle patrzę.

`Request URL: https://www.rozkladzik.pl/poznan/timetable.txt?c=bs&l=146&d=1&b=5&sid=55924&day=2`

**Comment by PiotrMachowski** [comment]
Pole `sid` to identyfikator miasta, także to nie to. Widzę, że w Twoim linku parametr `c` ma wartość `bs`, nie udało mi się wyklikać takiego przypadku. Na ten moment nie jestem też w stanie osiągnąć wartości `55917`, także nie wiem, skąd ją wziąłem. Poniżej linki, jakie znalazłem:


Przystanki:
```
Szarych Szeregów (SZSZ01):   https://www.rozkladzik.pl/poznan/timetable.txt?c=tsa&t=3114&sid=55924&day=2&time=641
Szarych Szeregów (SZSZ02):   https://www.rozkladzik.pl/poznan/timetable.txt?c=tsa&t=3132&sid=55924&day=2&time=641
Szarych Szeregów I (SS I01): https://www.rozkladzik.pl/poznan/timetable.txt?c=tsa&t=3113&sid=55924&day=2&time=641
Szarych Szeregów I (SS I02): https://www.rozkladzik.pl/poznan/timetable.txt?c=tsa&t=3133&sid=55924&day=2&time=641
```

Grupy przystanków:
```
Szarych Szeregów:   https://www.rozkladzik.pl/poznan/timetable.txt?c=bsa&b=144&sid=55924&day=2&time=641
Szarych Szeregów I: https://www.rozkladzik.pl/poznan/timetable.txt?c=bsa&b=143&sid=55924&day=2&time=641
```

**Comment by pniewiadowski** [comment]
@PiotrMachowski możesz wrzucić jakiegoś screena gdzie klikałeś, że dostałeś te linki? Nie mogę znaleźć tego na stronie :/

**Comment by PiotrMachowski** [comment]
Nie ma problemu :)

![image](https://user-images.githubusercontent.com/6118709/99728651-0b7da780-2aba-11eb-8de8-b9511864e988.png)

![image](https://user-images.githubusercontent.com/6118709/99728823-50a1d980-2aba-11eb-86ba-334edd69b371.png)

**Comment by pniewiadowski** [comment]
Dzięki.

Mam jeszcze problem z czymś takim, bo chce ustawić przystanek dla różnych linii, w różnych kierunkach, ale ma ten sam ID i w logach HA widzę, że ignoruje dodanie kolejnej encji:

Linia 168 przystanek Rzepeckiej w kierunku Dworzec Główny
Linia 183 przystanek Rzepeckiej w kierunku Rondo Śródka

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:490
Integration: Sensor (documentation, issues)
First occurred: 11:52:23 AM (1 occurrences)
Last logged: 11:52:23 AM
Entity id already exists - ignoring: sensor.rozkladzik_poznan_3612`

**Comment by PiotrMachowski** [comment]
Aktualnie id encji jest tworzone na podstawie schematu: `{platform_name}_{city}_{stop_id}`. Musiałbym zmienić schemat generowania identyfikatorów, ewentualnie możesz to obejs - zrobić je w osobnej grupie sensorów. Przykład poniżej.

Zamiast:
```
sensor:
  - platform: rozkladzik
    city: 'poznan'
    stops:
      - id: 1234
        lines: ["168"]
        directions: ["Dworzec Główny"]
      - id: 1234
        lines: ["183"]
        directions: ["Rondo Śródka"]
```

zrób:
```
sensor:
  - platform: rozkladzik
    city: 'poznan'
    name: "Rozkładzik 1"
    stops:
      - id: 1234
        lines: ["168"]
        directions: ["Dworzec Główny"]
  - platform: rozkladzik
    city: 'poznan'
    name: "Rozkładzik 2"
    stops:
      - id: 1234
        lines: ["183"]
        directions: ["Rondo Śródka"]
```

**Comment by pniewiadowski** [comment]
Dziękuje Piotr, to sprytne rozwiązanie.

Niestety teraz mam taki problem a z tym już pewnie za wiele zdziałać nie będziemy mogli, prawda?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rozkladzik/sensor.py", line 49, in setup_platform
    dev.append(RozkladzikSensor(entity_id, name, city, stop_id, stop_name, group_mode, lines, directions))
  File "/config/custom_components/rozkladzik/sensor.py", line 60, in __init__
    self._city_data = self.get_city_data()
  File "/config/custom_components/rozkladzik/sensor.py", line 177, in get_city_data
    response = requests.get(url_template.format(self._city))
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.rozkladzik.pl', port=443): Max retries exceeded with url: /poznan/data.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa64252e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Home Assistant has started!
`

**Comment by PiotrMachowski** [comment]
Rozumiem, że z tą konfiguracją zadziało?
Tutaj jest problem z blokadą od strony Rozkładzika, tego już się nie przeskoczy

**Comment by pniewiadowski** [comment]
Mam wrażenie, że po tym jak powieliłem konfigurację to dostałem BANa. Napisałem do rozkładzika, może ściągną :)

**Comment by PiotrMachowski** [comment]
Ban sam znika po pewnym czasie :) nie wiem, czy ściągną, bo wydaje mi się, że to z powodu tej integracji dodali banowanie ;)

**Comment by filipcy** [comment]
czesc, 

probuje ustawic rozkladzik dla polaczen w Poznaniu, ale jakkolwiek nie ustawilbym id, zwraca mi brak polaczeń. Przyklad konfiguracji jakiej uzylem
```
 - platform: rozkladzik
    city: 'poznan'
    stops:
      - id: 3055
        name: 'Slowianska'
        lines:
          - 16
        directions:
          - "Franowo"
```



Probowalem tez z uzyciem przystanku grupowego, ale taki sam efekt

```
- platform: rozkladzik
    city: 'poznan'
    stops:
      - id: 109
        name: 'Slowianska'
        stops_group_mode: true
        lines:
          - 16
        directions:
          - "Franowo"
 ```

z gory dzieki za podpowiedz co zle robie :)

To widze w HA

```
html_timetable: >-
  <table width="100%" border=1 style="border: 1px black solid; border-collapse:
  collapse;">

  <tr><td style="text-align: center; padding: 4px">Brak połączeń</td></table>
html: >-
  <table width="100%" border=1 style="border: 1px black solid; border-collapse:
  collapse;">

  <tr><td style="text-align: center; padding: 4px">Brak połączeń</td></table>
html_departures: >-
  <table width="100%" border=1 style="border: 1px black solid; border-collapse:
  collapse;">

  </table>
friendly_name: Rozkładzik poznan - Slowianska

**Comment by PiotrMachowski** [comment]
@filipcy 
Takie coś zadziała:
```yaml
 - platform: rozkladzik
    city: 'poznan'
    stops:
      - id: 3055
        name: 'Slowianska'
        lines:
          - "16"
        directions:
          - "Franowo"
```
